In [1]:
import pandas as pd
import numpy as np

In [15]:
from src.dataUtils import impute

dataset = './data/SIDI_Full.csv'
df = impute.impute(dataset, cols='DI')
df = pd.get_dummies(df, columns=['LD'])

df.head()

Checking NaNs:
LD                 0
Velocity (km/s)    0
a (degrees)        0
$ (degrees)        0
DI                 0
dtype: int64
Checking zeros:
   0       0.00007
1       0.00580
2       0.01259
3       0.02086
4       0.02278
         ...   
1630    0.30280
1631    0.54222
1632    0.72227
1633    0.83957
1634    0.92741
Name: DI, Length: 1635, dtype: float64 has: 13 zeros


Velocity (km/s)  a (degrees)  $ (degrees)       DI  Imputed  LD_1.0  \
0             0.25         90.0         75.0  0.00007      0.0       1   
1             0.25         90.0         60.0  0.00580      0.0       1   
2             0.25         90.0         45.0  0.01259      0.0       1   
3             0.25         90.0         30.0  0.02086      0.0       1   
4             0.25         90.0         15.0  0.02278      0.0       1   

   LD_2.0  LD_4.0  
0       0       0  
1       0       0  
2       0       0  
3       0       0  
4       0       0

In [18]:
import torch

n_data = df.to_numpy()
t_data = torch.tensor(n_data)
t_data

tensor([[  0.2500,  90.0000,  75.0000,  ...,   1.0000,   0.0000,   0.0000],
        [  0.2500,  90.0000,  60.0000,  ...,   1.0000,   0.0000,   0.0000],
        [  0.2500,  90.0000,  45.0000,  ...,   1.0000,   0.0000,   0.0000],
        ...,
        [  2.1500, -90.0000,  45.0000,  ...,   0.0000,   0.0000,   1.0000],
        [  2.1500, -90.0000,  30.0000,  ...,   0.0000,   0.0000,   1.0000],
        [  2.1500, -90.0000,  15.0000,  ...,   0.0000,   0.0000,   1.0000]],
       dtype=torch.float64)

In [19]:
data_mean = torch.mean(t_data, dim=0)
data_mean

tensor([1.2068e+00, 1.8349e-01, 3.7569e+01, 3.8409e-01, 7.9511e-03, 3.3333e-01,
        3.3333e-01, 3.3333e-01], dtype=torch.float64)

In [20]:
data_var = torch.var(t_data, dim=0)
data_var

tensor([3.9922e-01, 3.1425e+03, 6.5527e+02, 8.2845e-02, 7.8927e-03, 2.2236e-01,
        2.2236e-01, 2.2236e-01], dtype=torch.float64)

In [22]:
data_norm = (t_data - data_mean) / torch.sqrt(data_var)
data_norm

tensor([[-1.5144,  1.6022,  1.4623,  ...,  1.4138, -0.7069, -0.7069],
        [-1.5144,  1.6022,  0.8763,  ...,  1.4138, -0.7069, -0.7069],
        [-1.5144,  1.6022,  0.2903,  ...,  1.4138, -0.7069, -0.7069],
        ...,
        [ 1.4927, -1.6087,  0.2903,  ..., -0.7069, -0.7069,  1.4138],
        [ 1.4927, -1.6087, -0.2957,  ..., -0.7069, -0.7069,  1.4138],
        [ 1.4927, -1.6087, -0.8817,  ..., -0.7069, -0.7069,  1.4138]],
       dtype=torch.float64)

In [24]:
data_norm = pd.DataFrame(data_norm)
data_norm.head()

0         1         2         3         4         5         6  \
0 -1.514384  1.602199  1.462256 -1.334202 -0.089498  1.413781 -0.706891   
1 -1.514384  1.602199  0.876279 -1.314294 -0.089498  1.413781 -0.706891   
2 -1.514384  1.602199  0.290301 -1.290704 -0.089498  1.413781 -0.706891   
3 -1.514384  1.602199 -0.295677 -1.261971 -0.089498  1.413781 -0.706891   
4 -1.514384  1.602199 -0.881655 -1.255301 -0.089498  1.413781 -0.706891   

          7  
0 -0.706891  
1 -0.706891  
2 -0.706891  
3 -0.706891  
4 -0.706891